site_name: Azin cloud documentation
site_description: Official documentation for Azin cloud products
site_url: https://v3docs.azintelecom.az
theme:
  name: material
  features:
    - tabs
    - search.suggest
  #dark theme
  # palette:
  #   scheme: slate

nav:
  - AzCloud:
    - Home: index.md
    - Getting started: ui/create-vm.md
  - CLI:
    - Getting started: cli/intro.md
    - Create virtual machine: cli/create-vm.md
    - Usage: cli/usage.md
    - Automation: cli/automation.md
    - Apps: cli/apps.md
  - UI:
    - Projects: ui/projects.md
    - Quota: ui/quota.md
    - Power: ui/power.md
    - VMRC: ui/vmrc.md
    - Mount custom ISO: ui/mount-iso.md
    - CPU: ui/cpu.md
    - RAM: ui/ram.md
    - Storage: ui/storage.md
    - Networks: ui/networks.md
    - Snapshots: ui/snapshots.md
    - Monitoring: ui/monitoring.md
    - Apps: ui/apps.md
    - Trash Bin: ui/bin.md
  - Releases: 
    - 3.0.0: releases/3.0.0.md


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false

plugins:
  - git-revision-date-localized
  - search

repo_name: Azintelecom/Azin-Cli
repo_url: https://github.com/Azintelecom/Azin-Cli

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Azintelecom
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/azintelecom-llc/