site_name: Azin cloud documentation
site_description: Official documentation for Azin cloud products
site_url: https://docs.azintelecom.az
theme:
  name: material
  features:
    - tabs
  #dark theme
  # palette:
  #   scheme: slate

nav:
  - AzCloud:
    - Home: index.md
    - Getting started: ui/create-vm.md
  - CLI:
    - Getting started: cli/intro.md
    - Create virtual machine: cli/create-vm.md
    - Usage: cli/usage.md
    - Automation: cli/automation.md
  - UI:
    - Mount custom ISO: ui/mount-iso.md
    - Apps: ui/apps.md
  - Releases: 
    - 3.0.0: releases/3.0.0.md


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false

plugins:
  - git-revision-date-localized

repo_name: Azintelecom/Azin-Cli
repo_url: https://github.com/Azintelecom/Azin-Cli

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Azintelecom
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/azintelecom-llc/